export const Langs:string[] = [
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "PHP",
    "TypeScript",
    "C++",
    "C",
    "Ruby",
    "Swift",
    "Objective-C",
    "Go",
    "Kotlin",
    "Shell",
    "R",
    "MATLAB",
    "Scala",
    "Rust",
    "Groovy",
    "Lua",
    "Dart",
    "HTML",
    "CSS",
    "SQL",
    "PL/SQL (Oracle)",
    "T-SQL (Microsoft SQL Server)",
    "Visual Basic",
    "Assembly",
    "MATLAB",
    "Shell Scripting",
    "Perl",
    "Haskell",
    "Delphi",
    "COBOL",
    "Fortran",
    "Ada",
    "TypeScript",
    "CoffeeScript",
    "Kotlin",
    "Dart",
    "Objective-C",
    "ActionScript",
    "F#",
    "Scheme",
    "Lisp",
    "Erlang",
    "Prolog",
    "Apex (Salesforce)",
    "ABAP",
    "Solidity (Ethereum)"
  ]
  